# Generated by Django 4.1 on 2023-08-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.CharField(max_length=50)),
                ('sort_no', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
                ('korean_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('version_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculums',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(max_length=50)),
                ('feature_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('curriculum', models.CharField(max_length=50)),
                ('chapter_id', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=150)),
                ('idx', models.CharField(max_length=150)),
                ('lecture_idx', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='FeatureProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(max_length=50)),
                ('problem_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'featureproblems',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.CharField(max_length=50)),
                ('lecture', models.IntegerField()),
                ('lec_title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lectures',
            },
        ),
        migrations.CreateModel(
            name='LectureIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.CharField(max_length=50)),
                ('problem_id', models.IntegerField()),
                ('lecture_id', models.IntegerField()),
                ('lecture_idx', models.CharField(max_length=100)),
                ('end_idx', models.IntegerField()),
                ('page', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lectureindices',
            },
        ),
        migrations.CreateModel(
            name='LectureTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.CharField(max_length=50)),
                ('lecture_id', models.IntegerField()),
                ('temp', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lecturetemps',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_id', models.IntegerField()),
                ('elements', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('type2', models.CharField(max_length=100)),
                ('type3', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=200)),
                ('random', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'problems',
            },
        ),
        migrations.CreateModel(
            name='RevStruct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField()),
                ('child', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'revstructs',
            },
        ),
    ]
