# Generated by Django 4.1 on 2023-08-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_feature_category_alter_feature_chapter_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='korean_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='short_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='sort_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='version_code',
            field=models.IntegerField(null=True),
        ),
    ]
